version: '3.8'

services:
  app:
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/house_hunter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - house-hunter-m2-cache:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - house-hunter-db-data:/var/lib/postgresql/data
      - ./src/main/resources/db/migrations/InitialiseDbData.sql:/docker-entrypoint-initdb.d/InitialiseDbData.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: house_hunter
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  house-hunter-m2-cache:
  house-hunter-db-data:
